name: Expose SSH with Ngrok

on:
  workflow_dispatch:
  push:

jobs:
  ssh-server:
    runs-on: ubuntu-latest

    steps:
    - name: Install OpenSSH Server
      run: sudo apt-get update && sudo apt-get install openssh-server -y

    - name: Set up SSH authorized_keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/authorized_keys

    - name: Start SSH server
      run: sudo systemctl start ssh

    - name: Install jq
      run: sudo apt-get install jq -y

    - name: Download and Install Ngrok
      run: |
        curl -o ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xzf ngrok.tgz
        sudo mv ngrok /usr/local/bin/

    - name: Start Ngrok tunnel
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TUNNEL_TOKEN }}
      run: |
        ngrok config add-authtoken $NGROK_AUTH_TOKEN
        nohup ngrok tcp 22 > ngrok.log &
        sleep 10
        curl http://localhost:4040/api/tunnels > tunnels.json
        cat tunnels.json

    - name: Extract Public URL
      run: |
        public_url=$(jq -r '.tunnels[] | select(.proto == "tcp") | .public_url' tunnels.json)
        host=$(echo $public_url | cut -d'/' -f3 | cut -d':' -f1)
        port=$(echo $public_url | cut -d':' -f3)
        echo "🔗 SSH into the runner using: ssh -p $port runner@$host"

    - name: Keep Alive
      run: |
        echo "⏳ Sleeping to keep tunnel alive for 6 hours..."
        sleep 21600
